# Tensorflow2.0 小练习
# 改为pytorch的标准库作为对照


In [3]:
import torch
import numpy as np

## 实现softmax函数

In [ ]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))   # 减去最大值，防止e指数溢出，同时不影响结果
    prob_x = exp_x / np.sum(exp_x, axis=-1, keepdims=True)
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data) - torch.nn.functional.softmax(torch.tensor(test_data), dim=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [11]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    prob_x = 1 / (1 + np.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data) - torch.sigmoid(torch.tensor(test_data)).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [ ]:

def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss = -np.sum(label * np.log(x + 1e-9)) / x.shape[0]  # 加入一个小常数避免log(0)
    return loss

test_data = np.random.normal(size=[10, 5])
prob = torch.nn.functional.softmax(torch.tensor(test_data, dtype=torch.float32), dim=-1)

label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

# 使用 PyTorch 计算 softmax 交叉熵损失
label_tensor = torch.tensor(label, dtype=torch.float32)
loss_fn = torch.nn.CrossEntropyLoss()
loss_ce = loss_fn(torch.tensor(test_data, dtype=torch.float32), torch.argmax(label_tensor, dim=-1))

# 使用自定义 softmax_ce 函数计算交叉熵损失
numpy_loss = softmax_ce(prob.numpy(), label)


diff = (loss_ce.item() - numpy_loss) ** 2
diff < 0.0001

True

## 实现 sigmoid 交叉熵loss函数

In [22]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss = -np.mean(label * np.log(x + 1e-9) + (1 - label) * np.log(1 - x + 1e-9))
    return loss

test_data = np.random.normal(size=[10])
prob = torch.sigmoid(torch.tensor(test_data, dtype=torch.float32))

label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)


# 使用 PyTorch 计算 sigmoid 交叉熵损失（通过 BCEWithLogitsLoss）
label_tensor = torch.tensor(label, dtype=torch.float32)
criterion = torch.nn.BCEWithLogitsLoss()
loss_bce_logits = criterion(torch.tensor(test_data, dtype=torch.float32), label_tensor)

# 使用自定义 sigmoid_ce 计算交叉熵损失
numpy_loss = sigmoid_ce(prob.numpy(), label)

diff = (loss_bce_logits.item() - numpy_loss) ** 2
diff < 0.0001

[0. 1. 0. 0. 0. 1. 1. 1. 1. 0.]


True